# required
cluster_name        = "gremlin"
domain_name         = "blue.cloud"
region_name         = "us-south"
zone_name           = "us-south-2"
data_center_name    = "dal10"
cluster_key         = "../../secrets/cluster-key.rsa"
bastion_key         = "../../secrets/bastion-key.rsa"
pull_secret         = "../../secrets/pull-secret.txt"
resource_group_name = "ibm/j4zzcat"
transit_gateway_id  = "34d3a7fe-23a7-4925-b21c-0442cc796ec7"
