variable cluster_name        {}
variable domain_name         {}
variable region_name         {}
variable zone_name           {}
variable data_center_name    {}
variable resource_group_name {}
variable transit_gateway_id  {}
variable bastion_key         {}
variable cluster_key         {}
variable pull_secret         {}
